services:

  # ── BUILD ONLY ────────────────────────────────────────
  dst_base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: dst-base:latest
    profiles:
      - build

  # ══════════════════════════════════════════════════════
  # SERVER 1 — DSTWhalesCluster (профіль: server1)
  # ══════════════════════════════════════════════════════
  dst_master:
    container_name: dst_master
    build: .
    networks:
      - dst_cluster1
    ports:
      - "10999:10999/udp"
    volumes:
      - ./clusters/server1:/home/dst/.klei/DoNotStarveTogether
    environment:
      - CLUSTER_NAME=DSTWhalesCluster
      - SHARD_NAME=Master
    stdin_open: true
    tty: true
    profiles:
      - server1
      - all

  dst_caves:
    container_name: dst_caves
    build: .
    networks:
      - dst_cluster1
    links:
      - dst_master
    ports:
      - "10998:10998/udp"
    volumes:
      - ./clusters/server1:/home/dst/.klei/DoNotStarveTogether
    environment:
      - CLUSTER_NAME=DSTWhalesCluster
      - SHARD_NAME=Caves
    profiles:
      - server1
      - all

  # ══════════════════════════════════════════════════════
  # SERVER 2 — DSTCluster2 (профіль: server2)
  # ══════════════════════════════════════════════════════
  dst_master2:
    container_name: dst_master2
    build: .
    networks:
      - dst_cluster2
    ports:
      - "11000:11000/udp"
    volumes:
      - ./clusters/server2:/home/dst/.klei/DoNotStarveTogether
    environment:
      - CLUSTER_NAME=DSTCluster2
      - SHARD_NAME=Master
    stdin_open: true
    tty: true
    profiles:
      - server2
      - all

  dst_caves2:
    container_name: dst_caves2
    build: .
    networks:
      - dst_cluster2
    links:
      - dst_master2
    ports:
      - "10997:10997/udp"
    volumes:
      - ./clusters/server2:/home/dst/.klei/DoNotStarveTogether
    environment:
      - CLUSTER_NAME=DSTCluster2
      - SHARD_NAME=Caves
    profiles:
      - server2
      - all

  # ══════════════════════════════════════════════════════
  # SERVER 3 — DSTCluster3 (профіль: server3)
  # ══════════════════════════════════════════════════════
  dst_master3:
    container_name: dst_master3
    build: .
    networks:
      - dst_cluster3
    ports:
      - "11001:11001/udp"
    volumes:
      - ./clusters/server3:/home/dst/.klei/DoNotStarveTogether
    environment:
      - CLUSTER_NAME=DSTCluster3
      - SHARD_NAME=Master
    stdin_open: true
    tty: true
    profiles:
      - server3
      - all

  dst_caves3:
    container_name: dst_caves3
    build: .
    networks:
      - dst_cluster3
    links:
      - dst_master3
    ports:
      - "10996:10996/udp"
    volumes:
      - ./clusters/server3:/home/dst/.klei/DoNotStarveTogether
    environment:
      - CLUSTER_NAME=DSTCluster3
      - SHARD_NAME=Caves
    profiles:
      - server3
      - all

networks:
  dst_cluster1:
  dst_cluster2:
  dst_cluster3: